name: Update Config Rules

on:
  schedule:
    - cron: '0 0 1,15 * *'
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  update-rules:
    name: Update Rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install packages
        run: |
          cd scripts/config-rule-updater
          pip install -r requirements.txt
          python index.py

  # get-changes:
  #   name: Get Changed Files
  #   runs-on: ubuntu-latest
  #   outputs:
  #     any_changed: ${{ steps.changed-files.outputs.any_changed }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 1
  #     - name: Get changed files
  #       id: changed-files
  #       uses: tj-actions/changed-files@v44
  #       with:
  #         files: |
  #           managed_rules_locals.tf
  #           managed_rules_variables.tf