name: Update Config Rules

on:
  schedule:
    - cron: '0 0 1,15 * *'
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write

jobs:
  update-rules:
    name: Update Rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Update rules
        id: update-rules
        run: |
          cd scripts/config-rule-updater
          pip install -r requirements.txt
          python index.py
      # - name: Get changed files
      #   id: get-changes
      #   uses: tj-actions/changed-files@v44
      #   with:
      #     files: |
      #       **/managed_rules_*.tf
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Automatic updates to AWS managed Config Rules
          delete-branch: true
          title: '[Auto] Update AWS Config Rules'
          assignees: bensonce
          reviewers: |
            bensonce
            duraikkannuv2

  # get-changes:
  #   name: Get Changed Files
  #   runs-on: ubuntu-latest
  #   outputs:
  #     any_changed: ${{ steps.changed-files.outputs.any_changed }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 1
  #     - name: Get changed files
  #       id: changed-files
  #       uses: tj-actions/changed-files@v44
  #       with:
  #         files: |
  #           managed_rules_locals.tf
  #           managed_rules_variables.tf
